# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20160113_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_likes',
            field=models.ManyToManyField(to='blog_app.Likes'),
        ),
    ]
