# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_no_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
