# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='no_likes',
            field=models.IntegerField(default=0),
        ),
    ]
