# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='pst',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='usr',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
