# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20160120_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('comnt', models.TextField()),
                ('pst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Post')),
            ],
        ),
    ]
