# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20160120_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ph_no',
            field=models.IntegerField(default=9191),
        ),
    ]
