# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_comments_tym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='tym',
        ),
    ]
