# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_remove_comments_tym'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='tym',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 15, 50, 6, 963499)),
        ),
    ]
