# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_comments_tym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='tym',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 27, 18, 57, 57, 7628)),
        ),
    ]
